### ISSUE TITLE
Openstack cluster update heat stack failed parsing template file

### ISSUE THREAD

**Issue by gainsley** [edgexr/edge-cloud-platform#241]
Updating an existing k8s cluster failed on an Openstack cloudlet when applying the new heat stack:
```
update failed: error udpating heat stack: xxx-main-xx-cluster-xxx-heat.yaml -- Error parsing template file:///xxx-main-xx-cluster-xxx-heat.yaml mapping values are not allowed here
    in "<unicode string>", line 192, column 21:
                  metadata:
```
The generated heat stack yaml (not included in full because it contains sensitive data) is incorrectly formatted. It appears the issue is incorrect indentation for the cloud-init section:
```
    xx-cluster.xxx.xxx.openxedge.net:
        type: OS::Nova::Server
        properties:
            name: xx-cluster.xxxx-main.xxx.openxedge.net
            networks:
                - port: { get_resource: xx-cluster.xxx-main.xxx.openxedge.net-external-network-shared-port }
            image: edgecloud-v5.0.0
            flavor: m4.medium
            config_drive: true
            user_data_format: RAW
            user_data: |
#cloud-config
chef:
  server_url: https://chef.openxedge.net/organizations/openxedge
  node_name: primary-xx-xx-cluster.xxx-main.xxx.openxedge.net
  environment: ""
  validation_name: mobiledgex-validator
  validation_key: /etc/chef/client.pem
....
  - path:  /etc/systemd/resolved.conf
    content: |
       [Resolve]
       DNS=1.1.1.1
       FallbackDNS=1.0.0.1
chpasswd: { expire: False }
ssh_pwauth: False
timezone: UTC
runcmd:
 - systemctl restart systemd-resolved
 - echo MOBILEDGEX doing ifconfig
 - ifconfig -a
            metadata:            <<<<<<<<<<<<<<<< line 193
                skipk8s: yes
                role: mex-agent-node
                k8smaster: 10.101.0.10
    mex-k8s-master-xxx-main-xx-cluster-xxx-shared-volume:
        type: OS::Cinder::Volume
        properties:
            name: mex-k8s-master-xxx-main-xx-cluster-xxx-shared-volume
            size: 30
```
