### ISSUE TITLE
Auto Scale down not working

### ISSUE THREAD

**Issue by mupasak** [edgexr/edge-cloud-platform#365]
We have been trying to validate the auto scale feature of edge cloud, we encountered that after scale up of clusters is happening fine, the auto scale down of the cluster is not happening. 

Setup:

The following k8s daemonset manifest was used to test the autoscale:

```
...
spec:
  replicas: 1
  selector:
    matchLabels:
      run: polinux-stress-k8s0.0.1
  template:
    metadata:
      labels:
        run: polinux-stress-k8s0.0.1
    spec:
      volumes:
      imagePullSecrets:
      - name: docker.io
      containers:
      - name: polinux-stress-k8s001
        image: docker.io/polinux/stress
        imagePullPolicy: Always
        command:
        - "stress"
        - "--cpu"
        - "8"
        - "--io"
        - "4"
        - "--vm"
        - "2"
        - "--vm-bytes"
        - "128M"
        - "--timeout"
        - "600s"
        ...
```

We ran a stress test command from k8s, with threshold set at the lowest. After some it due to the threshold being met, auto scale up is happening. Even after the command exits it does not auto scale down after that.

Expected behavior:

It should scale down once the resources are freed up as expected.
