### ISSUE TITLE
Integrate vulnerability scan in pipeline

### ISSUE THREAD

**Issue by a-da** [edgexr/edge-cloud-platform#445]
Document and implement the possible vulnerability scan in pipeline

### Where could we document this ?

Which repository ?
 
### Implementation: gitlab

_The below text was created by AI._

To integrate vulnerability scanning into your GitLab CI/CD pipeline, you can use GitLab’s built-in security scanners or add custom/external scanners. Here’s how you can do it:
1. Using GitLab’s Built-in Security Scanners

GitLab provides official security scanning templates for various types of vulnerabilities, including:

- SAST (Static Application Security Testing)
- DAST (Dynamic Application Security Testing)
- Dependency Scanning
- Container Scanning
- Secret Detection

How to add:

Add the following to your .gitlab-ci.yml using the include keyword to import the official templates:

```yaml
include:
    template: Security/SAST.gitlab-ci.yml
    template: Security/Dependency-Scanning.gitlab-ci.yml
    template: Security/Container-Scanning.gitlab-ci.yml
    template: Security/Secret-Detection.gitlab-ci.yml
    template: Security/DAST.gitlab-ci.yml

```
